### ISSUE TITLE
Extend appsettings and launch settings to support different environments

### ISSUE THREAD

**Issue by Nexitisyo** [rzLabs/Navislamia#14]
## Requirement
As a user, I would like to be able to have multiple environments with their own appsetting (syntax: appsettings.EnvironmentName.json)
to be able to e.g., work on an experimental server without interrupting other servers running on the same machine. 

## Infos:
With #13 the options pattern should be implemented. 
Currently, it's only possible to use appsettings.json which translates to the production environment.

## AC
* Create environments via CLI
    * command should create an appsettings.<environment-name>.json file
    *  (analyse if possible) create launch settings aswell

**Comment by Aodai** [comment]
I'll take over this task, I'm not sure if the creation of appsettings.{environment}.json should be in the scope of DevConsole. I feel like creating a small CLI tool to generate the config file would be nicer since it doesn't add bloat. What do you think about this?

Pinging @iSmokeDrow and @Nexitisyo

**Comment by Nexitisyo** [comment]
Isn't the creation of configs part of the command project?
